In [3]:
import numpy as np
import pandas as pd
import plotly.express as px

import warnings
warnings.filterwarnings('ignore')
import pandas as pd

data = {
    'month_number': [1, 2, 3, 4, 5],
    'facecream': [2500, 2630, 2140, 3400, 3600],
    'facewash': [1500, 1200, 1340, 1130, 1740],
    'toothpaste': [5200, 5100, 4550, 5870, 4560],
    'bathingsoap': [9200, 6100, 9550, 8870, 7760],
    'shampoo': [1200, 2100, 3550, 1870, 1560],
    'moisturizer': [1500, 1200, 1340, 1130, 1740],
    'total_units': [21100, 18330, 22470, 22270, 20960],
    'total_profit': [211000, 183300, 224700, 222700, 209600]
}

df = pd.DataFrame(data)

In [4]:
df.head()

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600

In [5]:
# month column --> df['month_number]) : x-axis
# total profit --> df['total_profit'] : y-axis
fig = px.line(df,
              x='month_number',
              y='total_profit',
              labels={'month_number':'Month Number',
                      'total_profit':'Total Profit'
                     }
             )
fig.show()

cette figure montre un schema de "reprise" en V

On remarque une forte baisse suivie d'un rebon marqué au dela des niveau d'avant la chute, puis un declin progressif, cela pourrait indiquer une correction du marché et une reprise

**ce qu'on doit retenir**
-schema en V reprise
-probléme: une chute du profit total
-Action requise: étude des actions, la periode, et les difficultés en preuve

In [6]:
import plotly.express as px
import pandas as pd

# Prepare the data for Plotly
data = pd.DataFrame({
    'Month Number': df['month_number'].tolist(),
    'Face Cream Sales': df['facecream'].tolist(),
    'Face Wash Sales': df['facewash'].tolist(),
    'Tooth Paste Sales': df['toothpaste'].tolist(),
    'Bathing Soap Sales': df['bathingsoap'].tolist(),
    'Shampoo Sales': df['shampoo'].tolist(),
    'Moisturizer Sales': df['moisturizer'].tolist()
})

# Melt the DataFrame to long format for Plotly Express
melted_data = data.melt(id_vars='Month Number',
                        var_name='Product',
                        value_name='Sales Units')

# Create the figure
fig = px.line(
    melted_data,
    x='Month Number',
    y='Sales Units',
    color='Product',
    #markers=True,
    title='Sales Data',
    labels={
        'Month Number': 'Month number',
        'Sales Units': 'Sales unit in number'
    }
)

fig.show()

Meilleure performance: "bathing soap" montrant schema reprise en V
performance moyenne: "tooth paste" montre une stability du profit
performance minimal: "shampoo" "moisturizer" "face cream"

In [14]:
import plotly.graph_objects as go

fig = go.Figure()

trace1 = go.Line(x=df["month_number"],
                    y=df["facecream"],
                    mode='lines',
                    name="Face Cream Sales"
                )
trace2 = go.Line(x=df["month_number"],
                 y=df["facewash"],
                 mode='lines',
                 name="Face Wash Sales"
                )
trace3 = go.Line(x=df["month_number"],
                 y=df["toothpaste"],
                 mode='lines',
                 name="Tooth Paste Sales"
                )
trace4 = go.Line(x=df["month_number"],
                 y=df["bathingsoap"],
                 mode='lines',
                 name="Bathing Soap Sales"
                )
trace5 = go.Line(x=df["month_number"],
                 y=df["shampoo"],
                 mode='lines',
                 name="Shampoo Sales"
                )
trace6 = go.Line(x=df["month_number"],
                 y=df["moisturizer"],
                 mode='lines',
                 name="Moisturizer Sales"
                )

fig.add_traces([trace1, trace2, trace3, trace4, trace5, trace6])
fig.update_layout(title="Sales Data",
                  xaxis_title="Month number",
                  yaxis_title="Sales unit in number")

fig.show()

In [8]:
fig = px.scatter(df,
                 x='month_number',
                 y='toothpaste'
                )
fig.show()

In [9]:
fig = px.bar(df,
              x='month_number',
              y='bathingsoap'
             )
fig.show()

In [10]:
fig = px.histogram(df,
             x='total_profit')

fig.show()



In Pie chart display Number of units sold per year for each product in percentage.

In [11]:
data = {
    'Face Cream': df['facecream'].sum(),
    'Face Wash': df['facewash'].sum(),
    'Tooth Paste': df['toothpaste'].sum(),
    'Bathing Soap': df['bathingsoap'].sum(),
    'Shampoo': df['shampoo'].sum(),
    'Moisturizer': df['moisturizer'].sum()
}

# Convert the data into a DataFrame for Plotly
sales_data = pd.DataFrame({
    'Product': data.keys(),
    'Sales': data.values()
})

# Create the pie chart
fig = px.pie(sales_data,
            names='Product',        # Labels for the pie chart
            values='Sales'         # Values for each section)
            )
fig.show()

**"Bathing soap** represente la meilleure vente en comparaison avec le reste des des produits, montrant une meilleur potentiel sur le long term, suivi par "tooth paste" avec une performance stable sur le long terme

## Read all product sales data and show it using the stack plot (area plot)

In [ ]:
# df

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600
5,6,2760,1555,4890,7490,1890,1555,20140,201400
6,7,2980,1120,4780,8980,1780,1120,29550,295500
7,8,3700,1400,5860,9960,2860,1400,36140,361400
8,9,3540,1780,6100,8100,2100,1780,23400,234000
9,10,1990,1890,8300,10300,2300,1890,26670,266700
10,11,2340,2100,7300,13300,2400,2100,41280,412800
11,12,2900,1760,7400,14400,1800,1760,30020,300200

In [12]:
# Prepare the data in long format
df_long = df.melt(id_vars=['month_number'],
                  value_vars=['facecream', 'facewash', 'toothpaste', 'bathingsoap', 'shampoo', 'moisturizer'],
                  var_name='Product',
                  value_name='Sales')

# Create the stacked area plot
fig = px.area(df_long,
              x='month_number',
              y='Sales',
              color='Product',
              title='All Product Sales Data',
              labels={'month_number': 'Month Number', 'Sales': 'Sales Units in Number'})

# Show the plot
fig.show()

In [13]:
import plotly.graph_objects as go

fig = go.Figure()

trace1 = go.Line(x=df["month_number"],
                    y=df["facecream"],
                    mode='lines',
                    fill='tozeroy',
                 stackgroup='one',
                    name="Face Cream Sales"
                )
trace2 = go.Line(x=df["month_number"],
                 y=df["facewash"],
                 mode='lines',
                 fill='tozeroy',
                 stackgroup='one',
                 name="Face Wash Sales"
                )
trace3 = go.Line(x=df["month_number"],
                 y=df["toothpaste"],
                 mode='lines',
                 fill='tozeroy',
                 stackgroup='one',
                 name="Tooth Paste Sales"
                )
trace4 = go.Line(x=df["month_number"],
                 y=df["bathingsoap"],
                 mode='lines',
                 fill='tozeroy',
                 stackgroup='one',
                 name="Bathing Soap Sales"
                )
trace5 = go.Line(x=df["month_number"],
                 y=df["shampoo"],
                 mode='lines',
                 fill='tozeroy',
                 stackgroup='one',
                 name="Shampoo Sales"
                )
trace6 = go.Line(x=df["month_number"],
                 y=df["moisturizer"],
                 mode='lines',
                 fill='tozeroy',
                 stackgroup='one',
                 name="Moisturizer Sales"
                )

fig.add_traces([trace1, trace2, trace3, trace4, trace5, trace6])
fig.update_layout(title="Sales Data",
                  xaxis_title="Month number",
                  yaxis_title="Sales unit in number",
                 )

fig.show()